// Workout actions
export const FETCH_WORKOUTS_REQUEST = 'FETCH_WORKOUTS_REQUEST';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const FETCH_WORKOUTS_FAILURE = 'FETCH_WORKOUTS_FAILURE';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const START_WORKOUT = 'START_WORKOUT';
export const END_WORKOUT = 'END_WORKOUT';
export const LOG_WORKOUT_SET = 'LOG_WORKOUT_SET';

// Exercise actions
export const FETCH_EXERCISES_REQUEST = 'FETCH_EXERCISES_REQUEST';
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS';
export const FETCH_EXERCISES_FAILURE = 'FETCH_EXERCISES_FAILURE';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

// Nutrition action types
export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';
export const ADD_MEAL = 'ADD_MEAL';
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const UPDATE_NUTRITION_GOALS = 'UPDATE_NUTRITION_GOALS';
export const ADD_FOOD_TO_MEAL = 'ADD_FOOD_TO_MEAL';
export const REMOVE_FOOD_FROM_MEAL = 'REMOVE_FOOD_FROM_MEAL';
export const UPDATE_MEALS = 'UPDATE_MEALS';
export const FETCH_CALORIE_DATA_REQUEST = 'FETCH_CALORIE_DATA_REQUEST';
export const FETCH_CALORIE_DATA_SUCCESS = 'FETCH_CALORIE_DATA_SUCCESS';
export const FETCH_CALORIE_DATA_FAILURE = 'FETCH_CALORIE_DATA_FAILURE';

// User actions
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const CONNECT_SMART_WATCH = 'CONNECT_SMART_WATCH';
export const DISCONNECT_SMART_WATCH = 'DISCONNECT_SMART_WATCH';

// Stats actions
export const FETCH_STATS_REQUEST = 'FETCH_STATS_REQUEST';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';