// Add these types to your existing action types

// Nutrition action types
export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';
export const ADD_MEAL = 'ADD_MEAL';
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const UPDATE_NUTRITION_GOALS = 'UPDATE_NUTRITION_GOALS';
export const ADD_FOOD_TO_MEAL = 'ADD_FOOD_TO_MEAL';
export const REMOVE_FOOD_FROM_MEAL = 'REMOVE_FOOD_FROM_MEAL';
export const UPDATE_MEALS = 'UPDATE_MEALS';
export const FETCH_CALORIE_DATA_REQUEST = 'FETCH_CALORIE_DATA_REQUEST';
export const FETCH_CALORIE_DATA_SUCCESS = 'FETCH_CALORIE_DATA_SUCCESS';
export const FETCH_CALORIE_DATA_FAILURE = 'FETCH_CALORIE_DATA_FAILURE';